use_frameworks!

platform :ios, '10.0'

target 'LKJsApiExternalIMP_Example' do
  pod 'LKJsApiExternalIMP', :path => '../'

  target 'LKJsApiExternalIMP_Tests' do
    inherit! :search_paths

    
  end
end
